# Site settings
title: UCLA Single Sign On Templates
email: carl@erutan.net
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: erutan
github_username:  erutan

# Build settings
markdown: kramdown
destination: _site

collections:
  ucla-logon-mocks:
    output: true
  medcenter-mocks:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "ucla-logon-mocks"
    values:
      layout: "ucla-logon"
  -
    scope:
      path: ""
      type: "medcenter-mocks"
    values:
      layout: "medcenter"