# Site settings
title: UCLA Single Sign On Templates
email: carl@erutan.net
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: erutan
github_username:  erutan

# Build settings
markdown: kramdown
pages: ./_pages